use crate::params::ParamValue;
use super::{ParamUIInfo, ParamUpdate, ModulationAction, ModSourceUI, ModAssignmentUI, AudioUIData, modulator_color};

/// Render parameter controls (sliders, checkboxes, color pickers) for a list of params.
/// Returns any param updates generated by user interaction.
pub fn render_params(
    ui: &mut egui::Ui,
    params: &[ParamUIInfo],
    modulation_sources: &[ModSourceUI],
    make_update: &dyn Fn(&str, ParamValue) -> ParamUpdate,
    make_mod_assign: Option<&dyn Fn(&str, usize) -> ModulationAction>,
    make_mod_remove: Option<&dyn Fn(&str) -> ModulationAction>,
    param_updates: &mut Vec<ParamUpdate>,
    modulation_actions: &mut Vec<ModulationAction>,
    id_prefix: &str,
    midi_learn_path_prefix: Option<&str>,
    midi_learn_start: &mut Option<String>,
    mod_assignments: &std::collections::HashMap<String, Vec<ModAssignmentUI>>,
    mod_current_values: &[f32],
    mod_param_prefix: &str,
) {
    for param in params {
        let label = param.label.as_ref().unwrap_or(&param.name);
        // Check if this param is modulated and get color info
        let mod_key = format!("{}:{}", mod_param_prefix, param.name);
        let assignments = mod_assignments.get(&mod_key);
        let is_modulated = assignments.map_or(false, |a| !a.is_empty());
        // Pick the primary modulator color (first assignment)
        let mod_label_color = assignments.and_then(|a| a.first()).map(|a| modulator_color(a.source_idx));
        match param.value {
            ParamValue::Float(mut v) => {
                let min = param.min.unwrap_or(0.0);
                let max = param.max.unwrap_or(1.0);
                ui.horizontal(|ui| {
                    // Color-code label if modulated
                    if let Some(color) = mod_label_color {
                        ui.label(egui::RichText::new(label).small().color(color));
                    } else {
                        ui.label(egui::RichText::new(label).small());
                    }
                    let slider_response = ui.add(egui::Slider::new(&mut v, min..=max).show_value(false));
                    if slider_response.changed() {
                        param_updates.push(make_update(&param.name, ParamValue::Float(v)));
                    }
                    // Draw modulation ghost indicator on top of slider
                    if is_modulated {
                        if let Some(assigns) = assignments {
                            let mut total_offset = 0.0f32;
                            for a in assigns {
                                if a.source_idx < mod_current_values.len() {
                                    total_offset += mod_current_values[a.source_idx] * a.amount;
                                }
                            }
                            let modulated_val = (v + total_offset).clamp(min, max);
                            let slider_rect = slider_response.rect;
                            let frac = (modulated_val - min) / (max - min);
                            let x = slider_rect.left() + frac * slider_rect.width();
                            let color = mod_label_color.unwrap_or(egui::Color32::YELLOW);
                            let painter = ui.painter();
                            // Vertical line at modulated value position
                            painter.line_segment(
                                [egui::pos2(x, slider_rect.top()), egui::pos2(x, slider_rect.bottom())],
                                egui::Stroke::new(2.0, color),
                            );
                        }
                    }
                    // Right-click context menu for MIDI learn
                    if let Some(prefix) = midi_learn_path_prefix {
                        slider_response.context_menu(|ui| {
                            let path = format!("{}/param/{}", prefix, param.name);
                            if ui.button("🎹 MIDI Learn").clicked() {
                                *midi_learn_start = Some(path);
                                ui.close_menu();
                            }
                        });
                    }
                    // Modulation assignment dropdown (only if sources exist and callbacks provided)
                    if !modulation_sources.is_empty() {
                        if let (Some(assign_fn), Some(remove_fn)) = (make_mod_assign, make_mod_remove) {
                            egui::ComboBox::from_id_salt(format!("mod_{}_{}", id_prefix, param.name))
                                .selected_text("🎛")
                                .width(30.0)
                                .show_ui(ui, |ui| {
                                    ui.label(egui::RichText::new("Assign Modulation").small().strong());
                                    for (src_idx, src) in modulation_sources.iter().enumerate() {
                                        let color = modulator_color(src_idx);
                                        let src_name = match src {
                                            ModSourceUI::LFO { .. } => format!("LFO {}", src_idx + 1),
                                            ModSourceUI::Audio { band, .. } => format!("Audio {:?}", band),
                                            ModSourceUI::ADSR { .. } => format!("ADSR {}", src_idx + 1),
                                            ModSourceUI::StepSequencer { .. } => format!("StepSeq {}", src_idx + 1),
                                        };
                                        if ui.button(egui::RichText::new(&src_name).color(color)).clicked() {
                                            modulation_actions.push(assign_fn(&param.name, src_idx));
                                        }
                                    }
                                    ui.separator();
                                    if ui.button("Clear").clicked() {
                                        modulation_actions.push(remove_fn(&param.name));
                                    }
                                });
                        }
                    }
                });
            }
            ParamValue::Bool(mut v) => {
                if ui.checkbox(&mut v, egui::RichText::new(label).small()).changed() {
                    param_updates.push(make_update(&param.name, ParamValue::Bool(v)));
                }
            }
            ParamValue::Color(c) => {
                let mut color = [c[0], c[1], c[2], c[3]];
                ui.horizontal(|ui| {
                    ui.label(egui::RichText::new(label).small());
                    if ui.color_edit_button_rgba_unmultiplied(&mut color).changed() {
                        param_updates.push(make_update(&param.name, ParamValue::Color(color)));
                    }
                });
            }
            _ => {} // Long, Point2D — not yet handled
        }
    }
}

/// Render effect parameter controls with optional modulation assignment
pub fn render_effect_params(
    ui: &mut egui::Ui,
    params: &[ParamUIInfo],
    modulation_sources: &[ModSourceUI],
    make_update: &dyn Fn(&str, ParamValue) -> ParamUpdate,
    make_mod_assign: Option<&dyn Fn(&str, usize) -> ModulationAction>,
    make_mod_remove: Option<&dyn Fn(&str) -> ModulationAction>,
    param_updates: &mut Vec<ParamUpdate>,
    modulation_actions: &mut Vec<ModulationAction>,
    id_prefix: &str,
    midi_learn_path_prefix: Option<&str>,
    midi_learn_start: &mut Option<String>,
    mod_assignments: &std::collections::HashMap<String, Vec<ModAssignmentUI>>,
    mod_current_values: &[f32],
    mod_param_prefix: &str,
) {
    for param in params {
        let label = param.label.as_ref().unwrap_or(&param.name);
        let mod_key = format!("{}:{}", mod_param_prefix, param.name);
        let assignments = mod_assignments.get(&mod_key);
        let is_modulated = assignments.map_or(false, |a| !a.is_empty());
        let mod_label_color = assignments.and_then(|a| a.first()).map(|a| modulator_color(a.source_idx));
        match param.value {
            ParamValue::Float(mut v) => {
                let min = param.min.unwrap_or(0.0);
                let max = param.max.unwrap_or(1.0);
                ui.horizontal(|ui| {
                    if let Some(color) = mod_label_color {
                        ui.label(egui::RichText::new(label).small().weak().color(color));
                    } else {
                        ui.label(egui::RichText::new(label).small().weak());
                    }
                    let slider_resp = ui.add(egui::Slider::new(&mut v, min..=max).show_value(false));
                    if slider_resp.changed() {
                        param_updates.push(make_update(&param.name, ParamValue::Float(v)));
                    }
                    // Draw modulation ghost indicator
                    if is_modulated {
                        if let Some(assigns) = assignments {
                            let mut total_offset = 0.0f32;
                            for a in assigns {
                                if a.source_idx < mod_current_values.len() {
                                    total_offset += mod_current_values[a.source_idx] * a.amount;
                                }
                            }
                            let modulated_val = (v + total_offset).clamp(min, max);
                            let slider_rect = slider_resp.rect;
                            let frac = (modulated_val - min) / (max - min);
                            let x = slider_rect.left() + frac * slider_rect.width();
                            let color = mod_label_color.unwrap_or(egui::Color32::YELLOW);
                            let painter = ui.painter();
                            painter.line_segment(
                                [egui::pos2(x, slider_rect.top()), egui::pos2(x, slider_rect.bottom())],
                                egui::Stroke::new(2.0, color),
                            );
                        }
                    }
                    if let Some(prefix) = midi_learn_path_prefix {
                        slider_resp.context_menu(|ui| {
                            let path = format!("{}/param/{}", prefix, param.name);
                            if ui.button("🎹 MIDI Learn").clicked() {
                                *midi_learn_start = Some(path);
                                ui.close_menu();
                            }
                        });
                    }
                    // Modulation assignment dropdown
                    if !modulation_sources.is_empty() {
                        if let (Some(assign_fn), Some(remove_fn)) = (make_mod_assign, make_mod_remove) {
                            egui::ComboBox::from_id_salt(format!("mod_{}_{}", id_prefix, param.name))
                                .selected_text("🎛")
                                .width(30.0)
                                .show_ui(ui, |ui| {
                                    ui.label(egui::RichText::new("Assign Modulation").small().strong());
                                    for (src_idx, src) in modulation_sources.iter().enumerate() {
                                        let color = modulator_color(src_idx);
                                        let src_name = match src {
                                            ModSourceUI::LFO { .. } => format!("LFO {}", src_idx + 1),
                                            ModSourceUI::Audio { band, .. } => format!("Audio {:?}", band),
                                            ModSourceUI::ADSR { .. } => format!("ADSR {}", src_idx + 1),
                                            ModSourceUI::StepSequencer { .. } => format!("StepSeq {}", src_idx + 1),
                                        };
                                        if ui.button(egui::RichText::new(&src_name).color(color)).clicked() {
                                            modulation_actions.push(assign_fn(&param.name, src_idx));
                                        }
                                    }
                                    ui.separator();
                                    if ui.button("Clear").clicked() {
                                        modulation_actions.push(remove_fn(&param.name));
                                    }
                                });
                        }
                    }
                });
            }
            ParamValue::Bool(mut v) => {
                if ui.checkbox(&mut v, egui::RichText::new(label).small().weak()).changed() {
                    param_updates.push(make_update(&param.name, ParamValue::Bool(v)));
                }
            }
            ParamValue::Color(c) => {
                let mut color = [c[0], c[1], c[2], c[3]];
                ui.horizontal(|ui| {
                    ui.label(egui::RichText::new(label).small().weak());
                    if ui.color_edit_button_rgba_unmultiplied(&mut color).changed() {
                        param_updates.push(make_update(&param.name, ParamValue::Color(color)));
                    }
                });
            }
            _ => {}
        }
    }
}

/// Render audio level bars
pub fn render_audio_levels(ui: &mut egui::Ui, audio: &AudioUIData) {
    if audio.enabled {
        ui.horizontal(|ui| {
            ui.label("Vol:");
            ui.add(egui::ProgressBar::new(audio.level).desired_width(100.0));
        });
        ui.horizontal(|ui| {
            ui.label("Bass:");
            ui.add(egui::ProgressBar::new(audio.bass).desired_width(100.0).fill(egui::Color32::from_rgb(220, 60, 60)));
        });
        ui.horizontal(|ui| {
            ui.label("Mid:");
            ui.add(egui::ProgressBar::new(audio.mid).desired_width(100.0).fill(egui::Color32::from_rgb(60, 220, 60)));
        });
        ui.horizontal(|ui| {
            ui.label("High:");
            ui.add(egui::ProgressBar::new(audio.treble).desired_width(100.0).fill(egui::Color32::from_rgb(60, 60, 220)));
        });
        if let Some(bpm) = audio.bpm {
            ui.horizontal(|ui| {
                ui.label(format!("BPM: {:.0}", bpm));
                ui.add(egui::ProgressBar::new(audio.beat_phase).desired_width(50.0).fill(egui::Color32::from_rgb(255, 165, 0)));
            });
        }
    } else {
        ui.label("⚠ No audio input");
    }
}

